apiVersion: v1
kind: Service
metadata:
  name: quelpoke
  namespace: albanc
spec:
  selector:
    app.kubernetes.io/name: quelpoke-albanc
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 80
      targetPort: 8080
